#ifndef AUTOREGRESSION_GLOBAL_H
#define AUTOREGRESSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUTOREGRESSION_LIBRARY)
#  define AUTOREGRESSIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUTOREGRESSIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOREGRESSION_GLOBAL_H
